name: CI
on: push
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "14.x"
    - name: Install packages
      run: npm install
    - name: Lint
      run: npm run lint:all
  build:
    runs-on: ubuntu-latest
    needs: lint
    - name: Build
      run: npm run build
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build,lint]
  #   - name: Deploy to netlify
  #     uses: netlify/actions/cli@master
  #     env:
  #       NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  #       NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
  #     with:
  #       args: deploy --dir=build --prod
  #       secrets: '["DEV_NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'