name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Linter
        run: npm run lint:all